swagger: "2.0"
info:
  title: My Portfolio API
  description: My portfolio api documentation
  version: 0.7

schemes: [http, https]

paths:
  /api/projects:
    get:
      tags:
        - Projects
      summary: Return list of projects
      description: Is returning array of projects in database
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              type: object
              properties:
                _id:
                  type: string
                name:
                  type: string
                description:
                  type: string
                image:
                  type: string
                project_id:
                  type: string
        400:
          description: Client Error
        500:
          description: Server Error

  /api/projects/{projectId}:
    get:
      tags:
        - Projects
      summary: Return single project by projectId
      description: Is finding and returning single project by projectId in database
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              _id:
                type: string
              name:
                type: string
              description:
                type: string
              detailDescription:
                type: string
              image:
                type: string
              techStack:
                type: array
                items:
                  type: string
              links:
                type: array
                items:
                  type: string
              project_id:
                type: string
              createdAt:
                type: string
              updatedAt:
                type: string
              __v:
                type: integer
        404:
          description: Project Not Found
        500:
          description: Server Error

  /api/skills:
    get:
      tags:
        - Skills
      summary: Return list of skills
      description: Is returning array of skills in database
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              type: object
              properties:
                _id:
                  type: string
                name:
                  type: string
                image:
                  type: string
                skill_id:
                  type: string
        400:
          description: Client Error
        500:
          description: Server Error

  /api/skills/{skillId}:
    get:
      tags:
        - Skills
      summary: Return single skill by skillId
      description: Is finding and returning single skill by skillId in database
      parameters:
        - name: skillId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              _id:
                type: string
              name:
                type: string
              image:
                type: string
              skill_id:
                type: string
              createdAt:
                type: string
              updatedAt:
                type: string
              __v:
                type: integer
        404:
          description: Project Not Found
        500:
          description: Server Error